import { config as loadDotenv } from "dotenv";
import { z } from "zod";

// Dev convenience only: populate process.env from the repo-root .env before
// validating it below. compose.dev.yaml also reads that file directly for
// the Postgres/GreenMail containers, so this is the app's own copy of that
// load — a value already set in the environment (e.g. by a container
// orchestrator in production) always wins, since dotenv never overrides
// existing process.env entries. Missing file is fine; quiet keeps that case
// silent instead of logging "file not found".
loadDotenv({ path: new URL("../../../.env", import.meta.url).pathname, quiet: true });

/**
 * Fail-closed config per ADR-0009: PUBLIC_URL and MAIL_CREDENTIAL_KEY have no
 * default and the process refuses to boot without them. MAIL_BIND defaults to
 * loopback so the safe case needs no thought.
 */
const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PUBLIC_URL: z.url(),
  MAIL_CREDENTIAL_KEY: z.string().min(32, "MAIL_CREDENTIAL_KEY must be at least 32 bytes"),
  MAIL_BIND: z.string().default("127.0.0.1:3000"),
  DATABASE_URL: z.url(),
  /**
   * ADR-0012's instance-level attachment budget, in encoded (base64) bytes —
   * 25MB default, ~18MB of real files. Read once at boot and handed to
   * `routes/attachments.ts`/`routes/compose-config.ts`; never a per-User or
   * per-Mail-Account setting.
   */
  ATTACHMENT_BUDGET_BYTES: z.coerce
    .number()
    .int()
    .positive()
    .default(25 * 1024 * 1024),
  /**
   * Web Push's VAPID keypair (#53, ADR-0015): generated by the `generate-vapid-keys`
   * operator CLI command shipped in the image, never auto-generated into the
   * database — "auto-generating... would silently invalidate every
   * subscription on a volume-restore mismatch". Optional as a *pair*: an
   * instance that never runs the CLI simply never offers Web Push
   * (`GET /push/config` answers `vapidPublicKey: null`) rather than failing
   * closed the way `PUBLIC_URL`/`MAIL_CREDENTIAL_KEY` do — this is a layer on
   * top of an otherwise-working Client, not a requirement of one.
   */
  MAIL_VAPID_PUBLIC_KEY: z.string().optional(),
  MAIL_VAPID_PRIVATE_KEY: z.string().optional(),
  /** The `mailto:`/`https:` contact `web-push` requires alongside a VAPID keypair (RFC 8292's "sub" claim) — a push service's abuse contact if it ever needs one. */
  MAIL_VAPID_CONTACT: z.string().default("mailto:admin@localhost"),
});

export type Env = z.infer<typeof envSchema>;

export function loadEnv(source: NodeJS.ProcessEnv = process.env): Env {
  const result = envSchema.safeParse(source);
  if (!result.success) {
    console.error("Refusing to boot: invalid environment configuration.");
    console.error(z.prettifyError(result.error));
    process.exit(1);
  }
  if (
    (result.data.MAIL_VAPID_PUBLIC_KEY === undefined) !==
    (result.data.MAIL_VAPID_PRIVATE_KEY === undefined)
  ) {
    console.error(
      "Refusing to boot: MAIL_VAPID_PUBLIC_KEY and MAIL_VAPID_PRIVATE_KEY must be set together (or both left unset to disable Web Push).",
    );
    process.exit(1);
  }
  return result.data;
}
