/**
 * Fixed vocabulary the generator draws from. Split into two tiers on
 * purpose: COMMON_WORDS gives every message plausible filler text so the
 * corpus isn't degenerate, while NEEDLE_TERMS are a small set of distinctive
 * words seeded at controlled, varying frequency (see generate.ts) so the
 * search benchmarks have query terms of known selectivity to measure
 * against — "how fast is a query that matches 40,000 messages" vs. "one
 * that matches 12" are different questions, and both need real hits to ask.
 *
 * NEEDLE_TERMS must not appear in COMMON_WORDS: a needle that's also drawn
 * as ordinary filler text blows past its intended frequency (this bit us
 * once — see generate.test.ts's vocabulary-invariant test).
 */

export const FIRST_NAMES = [
  "Alice",
  "Ben",
  "Carla",
  "Deepak",
  "Elena",
  "Farid",
  "Grace",
  "Hiro",
  "Ines",
  "Jonas",
  "Kaya",
  "Liam",
  "Mira",
  "Noah",
  "Olga",
  "Priya",
  "Quinn",
  "Rosa",
  "Sami",
  "Tara",
  "Ugo",
  "Vera",
  "Wynn",
  "Xena",
  "Yusuf",
  "Zoe",
  "Anders",
  "Bianca",
  "Cyrus",
  "Dana",
] as const;

export const LAST_NAMES = [
  "Nguyen",
  "Kowalski",
  "Silva",
  "Muller",
  "Andersson",
  "Rossi",
  "Kim",
  "Haddad",
  "Fischer",
  "Ivanov",
  "Costa",
  "Berg",
  "Novak",
  "Suzuki",
  "Diallo",
  "Larsen",
  "Petrov",
  "Moreau",
  "Okafor",
  "Sato",
  "Vance",
  "Winter",
  "Cole",
  "Reyes",
  "Hartmann",
  "Doyle",
] as const;

export const DOMAINS = [
  "acme.example",
  "brightline.example",
  "coldbrewco.example",
  "delta-labs.example",
  "evergreen.example",
  "flowstate.example",
  "greylock.example",
  "harborview.example",
  "ironwood.example",
  "junctionpoint.example",
  "keystonecorp.example",
  "lumen.example",
  "northgate.example",
  "orchardhq.example",
  "prairiewind.example",
] as const;

export const COMMON_WORDS = [
  "the",
  "and",
  "for",
  "with",
  "this",
  "that",
  "have",
  "will",
  "your",
  "team",
  "please",
  "review",
  "attached",
  "meeting",
  "schedule",
  "update",
  "project",
  "thanks",
  "regards",
  "call",
  "week",
  "time",
  "let",
  "know",
  "sounds",
  "good",
  "morning",
  "afternoon",
  "follow",
  "up",
  "next",
  "steps",
  "draft",
  "final",
  "version",
  "notes",
  "feedback",
  "question",
  "asap",
  "budget",
  "client",
  "vendor",
  "contract",
  "payment",
  "due",
  "deadline",
  "status",
  "report",
  "summary",
  "action",
  "items",
  "agenda",
  "office",
  "remote",
  "travel",
  "flight",
  "hotel",
  "booking",
  "confirm",
  "thanks",
  "appreciate",
  "sorry",
  "delay",
  "issue",
  "fix",
  "bug",
  "release",
  "deploy",
  "staging",
  "production",
  "server",
  "config",
  "photos",
  "trip",
  "weekend",
  "dinner",
  "lunch",
  "coffee",
  "chat",
  "welcome",
  "training",
  "policy",
  "handbook",
  "reminder",
  "newsletter",
  "subscribe",
  "unsubscribe",
  "offer",
  "discount",
  "sale",
  "order",
  "shipping",
  "tracking",
  "delivery",
  "receipt",
  "account",
  "password",
  "security",
  "login",
  "verify",
  "settings",
  "preferences",
] as const;

/**
 * Distinctive terms with hand-picked, spread-out selectivity: some appear in
 * a large slice of the corpus, some in a handful of messages. Frequencies
 * are per-mille of messages containing the term (approximate — see
 * generate.ts's Zipf-weighted draw), giving benchmark queries at roughly
 * 15%, 4%, 1%, and <0.1% selectivity.
 */
export const NEEDLE_TERMS = [
  { term: "quarterly", weight: 15 },
  { term: "migration", weight: 12 },
  { term: "onboarding", weight: 10 },
  { term: "invoice", weight: 9 },
  { term: "roadmap", weight: 6 },
  { term: "retrospective", weight: 4 },
  { term: "gatekeeper", weight: 2 },
  { term: "kestrelproject", weight: 0.6 },
  { term: "brontide", weight: 0.15 },
  { term: "quillfeather", weight: 0.05 },
] as const;

export const SUBJECT_TEMPLATES = [
  "{word} for {name}",
  "Re: {word} {word}",
  "{word} update — {word}",
  "Quick question about {word}",
  "{name}: {word} {word}",
  "Fwd: {word} from {name}",
  "Notes from the {word} {word}",
  "{word} {word} — action needed",
  "Your {word} {word}",
  "[{word}] {word} {word}",
] as const;
